name: Alpha

on: push

env:
  RUNS_ON: ubuntu-24.04

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  job-one:
    name: Job One
    runs-on: $RUNS_ON
    steps:
    - name: List files
      run: ls .
    - name: List files
      run: ls -lah .
  job-two:
    name: Job Two
    runs-on: $RUNS_ON
    steps:
    - name: Print working directory
      run: pwd
  job-three:
    name: Job Three
    runs-on: $RUNS_ON
    steps:
    - name: Echo contexts
      run: |
        echo ${{ toJSON(github) }}
        echo ${{ toJSON(inputs) }}
        echo ${{ toJSON(env) }}
        echo ${{ toJSON(runner) }}
        echo ${{ toJSON(secrets) }}